"""
Precision Oncology Agent - Report Export Router
=================================================
Generate and export clinical reports in multiple formats: Markdown, JSON,
PDF, and FHIR R4.

Author: Adam Jones
Date: February 2026
"""

import io
import time
import logging
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, PlainTextResponse, JSONResponse
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

router = APIRouter(tags=["reports"])


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------
class GenerateReportRequest(BaseModel):
    question: str
    cancer_type: Optional[str] = None
    top_k: int = Field(default=10, ge=1, le=100)
    format: str = Field(
        default="markdown",
        description="Output format: markdown, json, or pdf",
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _record_event(event_type: str, details: dict):
    """Append an event to the in-memory event log."""
    try:
        from agent.api.routes.events import record_event

        record_event(event_type, details)
    except Exception:
        pass


async def _generate_markdown_report(state: dict, question: str,
                                     cancer_type: Optional[str],
                                     top_k: int) -> str:
    """Query the RAG engine and format the result as Markdown."""
    rag = state.get("rag_engine")
    if rag is None:
        raise HTTPException(status_code=503, detail="RAG engine not available")

    result = await rag.query(
        question=question,
        cancer_type=cancer_type,
        top_k=top_k,
    )

    lines = [
        "# Precision Oncology Report",
        "",
        f"**Query:** {question}",
    ]
    if cancer_type:
        lines.append(f"**Cancer Type:** {cancer_type}")
    lines.append("")
    lines.append("## Answer")
    lines.append("")
    lines.append(result.get("answer", "No answer generated."))
    lines.append("")
    lines.append("## Evidence Sources")
    lines.append("")

    for i, src in enumerate(result.get("sources", []), 1):
        coll = src.get("collection", "unknown")
        score = src.get("score", 0.0)
        text = src.get("text", "")[:200]
        lines.append(f"**{i}. [{coll}]** (score: {score:.3f})")
        lines.append(f"> {text}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Precision Oncology Intelligence Agent*")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@router.post("/api/reports/generate")
async def generate_report(req: GenerateReportRequest):
    """Generate a report from a clinical question in the requested format."""
    from agent.api.main import get_state

    state = get_state()
    t0 = time.time()

    try:
        md_content = await _generate_markdown_report(
            state, req.question, req.cancer_type, req.top_k
        )
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Report generation failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))

    elapsed_ms = round((time.time() - t0) * 1000, 1)

    _record_event(
        "report_generated",
        {"question": req.question, "format": req.format, "processing_time_ms": elapsed_ms},
    )

    if req.format == "json":
        return {"report": md_content, "format": "json", "processing_time_ms": elapsed_ms}
    elif req.format == "pdf":
        # Attempt PDF generation via reportlab; fall back to markdown
        try:
            from agent.src.export import markdown_to_pdf

            pdf_bytes = markdown_to_pdf(md_content)
            tmp_path = "/tmp/onco_report.pdf"
            with open(tmp_path, "wb") as f:
                f.write(pdf_bytes)
            return FileResponse(
                tmp_path,
                media_type="application/pdf",
                filename="oncology_report.pdf",
            )
        except ImportError:
            logger.warning("PDF export not available, returning markdown")
            return PlainTextResponse(md_content, media_type="text/markdown")
    else:
        return PlainTextResponse(md_content, media_type="text/markdown")


@router.get("/api/reports/{case_id}/{fmt}")
async def export_case_report(case_id: str, fmt: str):
    """Export a case report in the specified format (markdown, json, pdf, fhir)."""
    from agent.api.main import get_state

    state = get_state()
    case_manager = state.get("case_manager")
    if case_manager is None:
        raise HTTPException(status_code=503, detail="Case manager not initialised")

    # Retrieve case
    try:
        case = await case_manager.get_case(case_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    t0 = time.time()

    _record_event(
        "report_exported",
        {"case_id": case_id, "format": fmt},
    )

    # --- Markdown ---
    if fmt == "markdown" or fmt == "md":
        try:
            from agent.src.export import case_to_markdown

            md = case_to_markdown(case)
        except ImportError:
            md = f"# Case Report: {case_id}\n\n```json\n{case}\n```"
        return PlainTextResponse(md, media_type="text/markdown")

    # --- JSON ---
    if fmt == "json":
        elapsed_ms = round((time.time() - t0) * 1000, 1)
        return JSONResponse(
            {"case": case, "format": "json", "processing_time_ms": elapsed_ms}
        )

    # --- PDF ---
    if fmt == "pdf":
        try:
            from agent.src.export import case_to_markdown, markdown_to_pdf

            md = case_to_markdown(case)
            pdf_bytes = markdown_to_pdf(md)
            tmp_path = f"/tmp/onco_case_{case_id}.pdf"
            with open(tmp_path, "wb") as f:
                f.write(pdf_bytes)
            return FileResponse(
                tmp_path,
                media_type="application/pdf",
                filename=f"case_{case_id}.pdf",
            )
        except ImportError:
            raise HTTPException(
                status_code=501,
                detail="PDF export requires reportlab. Install with: pip install reportlab",
            )

    # --- FHIR R4 ---
    if fmt == "fhir":
        try:
            from agent.src.export import case_to_fhir_bundle

            bundle = case_to_fhir_bundle(case)
        except ImportError:
            # Minimal FHIR stub
            bundle = {
                "resourceType": "Bundle",
                "type": "document",
                "entry": [
                    {
                        "resource": {
                            "resourceType": "DiagnosticReport",
                            "status": "final",
                            "code": {
                                "text": f"Oncology Case {case_id}"
                            },
                            "conclusion": str(case),
                        }
                    }
                ],
            }
        return JSONResponse(bundle)

    raise HTTPException(
        status_code=400,
        detail=f"Unsupported format: {fmt}. Use markdown, json, pdf, or fhir.",
    )
